# version: '3'
# services:
#   database:
#     container_name: docker-postgres
#     image: postgres
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_USER=postgres 
#       - POSTGRES_PASSWORD=2505
#       - POSTGRES_DB=epatra

  # backend:
  #   image: server
  #   ports:
  #     - 5000:5000
  #   restart: unless-stopped
  #   expose:
  #     - 5000
  #   build:
  #     context: .
  #     dockerfile: ./server/Dockerfile
  #   depends_on:
  #     - database

  # frontend:
  #   container_name: frontend
  #   image: client
  #   build:
  #     context: ./client/
  #     dockerfile: Dockerfile
  #   # volumes:
  #   #   - './UI/.:/app'
  #   #   - '/app/node_modules'
  #   ports:
  #     - 3000:3000
  #   # environment:
  #     # - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - backend
  #     - database